/** @format */

import React, { useEffect, useState } from "react";
import {
  EffectComposer,
  Bloom,
  Vignette,
  ToneMapping,
  N8AO,
  LUT,
  SMAA,
} from "@react-three/postprocessing";
import { ToneMappingMode, LookupTexture } from "postprocessing";
import { TextureLoader, type Texture } from "three";

interface PostprocessingProps {
  enabled: boolean;
}

const LUT_URL = `${process.env.PUBLIC_URL}/luts/hall-wakandan.png`;

/** Postfx pipeline tuned for the Hall. Reuses the same effects + ordering as
 *  the Workstation, but drops DoF (the Hall's read is "open architectural
 *  hall" — pulling focus would shrink the read) and pushes Bloom a touch
 *  harder so the floor-glow rings and hologram fresnel rim carry.
 *
 *  Phase 8 polish: hall-specific Wakandan-dusk LUT mounted between Bloom
 *  and the tone mapper. Cools shadows toward navy-purple, warms highlights
 *  toward amber, +12% midtone saturation, slight gamma 0.92 contrast lift.
 *  Generated by `scripts/generate-lut-hall.mjs`.
 */
const Postprocessing: React.FC<PostprocessingProps> = ({ enabled }) => {
  const [lutTex, setLutTex] = useState<LookupTexture | null>(null);
  useEffect(() => {
    if (!enabled) return;
    let canceled = false;
    new TextureLoader().load(LUT_URL, (tex: Texture) => {
      if (canceled) {
        tex.dispose();
        return;
      }
      try {
        const lut = LookupTexture.from(tex);
        tex.dispose();
        setLutTex(lut);
      } catch {
        /* PNG decode failure — skip the LUT pass silently. */
      }
    });
    return () => {
      canceled = true;
    };
  }, [enabled]);

  if (!enabled) {
    return (
      <EffectComposer multisampling={0}>
        <ToneMapping mode={ToneMappingMode.ACES_FILMIC} />
      </EffectComposer>
    );
  }
  return (
    <EffectComposer multisampling={0}>
      <SMAA />
      <N8AO
        aoRadius={0.6}
        intensity={2.2}
        distanceFalloff={1.1}
        quality="medium"
      />
      <Bloom
        intensity={0.75}
        luminanceThreshold={0.6}
        luminanceSmoothing={0.22}
        mipmapBlur
        radius={0.85}
      />
      <Vignette eskil={false} offset={0.32} darkness={0.38} />
      {lutTex && <LUT lut={lutTex} tetrahedralInterpolation />}
      <ToneMapping mode={ToneMappingMode.ACES_FILMIC} />
    </EffectComposer>
  );
};

export default Postprocessing;
