"""Hall vista skybox HDRI bake — Session 26 (daylight Drakensberg).

Generates ``public/hdri/hall-vista.hdr`` — a 2048×1024 equirectangular
HDRI used by `Scene.tsx` as the IBL + background environment for the
Hall route. Session 26 rebuilds the panorama as a **soft daylight
Drakensberg** scene matching the canonical Hall of Zero Limits
reference (Marvel/Sprite Wakandan cathedral):

- Top hemisphere: light cyan zenith → pale azure mid-sky → warm
  cream-white horizon haze. Smooth multi-stop gradient.
- Mountain horizon band: low-frequency noise sculpts a lush-green
  Drakensberg ridge at elevation 0–5° above horizon. The mountains
  read as a green silhouette against the bright sky, framing the
  hub's outer-wall arched windows with a vista of distant peaks.
- Bottom hemisphere: olive ground tone with subtle noise.
- No stars — daytime panorama.

No geometry — the entire panorama is generated by a World shader,
baked via Cycles' equirectangular camera. Output is .hdr (Radiance
RGBE) since three.js + drei's `Environment` reads both .exr and .hdr;
.hdr is smaller on disk and renders identically as an IBL.

Run headless::

    blender -b -P blender/scripts/atmo/skybox-bake.py
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import bpy  # type: ignore[import-not-found]

_REPO_ROOT = Path(__file__).resolve().parents[3]
OUTPUT_HDR = _REPO_ROOT / "public" / "hdri" / "hall-vista.hdr"

RESOLUTION_X = 2048
RESOLUTION_Y = 1024
SAMPLES = 64


def _reset_scene() -> None:
    bpy.ops.wm.read_factory_settings(use_empty=True)


def _build_world_shader() -> None:
    """Build the procedural daylight Drakensberg panorama as a World
    shader. Drives background via geometry-incoming + math nodes on the
    panoramic UV."""
    world = bpy.data.worlds.get("Hall World")
    if world is None:
        world = bpy.data.worlds.new("Hall World")
    bpy.context.scene.world = world
    world.use_nodes = True
    nt = world.node_tree
    for n in list(nt.nodes):
        nt.nodes.remove(n)

    # Texture Coordinate → Generated → drives the gradient
    tex_coord = nt.nodes.new("ShaderNodeTexCoord")
    tex_coord.location = (-1400, 0)

    sep_xyz = nt.nodes.new("ShaderNodeSeparateXYZ")
    sep_xyz.location = (-1100, 100)
    nt.links.new(tex_coord.outputs["Generated"], sep_xyz.inputs["Vector"])

    # ColorRamp for the daylight gradient: olive ground bottom → warm
    # cream-white horizon haze → pale azure mid-sky → light cyan zenith.
    color_ramp = nt.nodes.new("ShaderNodeValToRGB")
    color_ramp.location = (-700, 0)
    cr = color_ramp.color_ramp
    cr.interpolation = "B_SPLINE"
    while len(cr.elements) > 1:
        cr.elements.remove(cr.elements[1])
    cr.elements[0].position = 0.0
    cr.elements[0].color = (0.080, 0.090, 0.060, 1.0)  # olive ground
    new_stops = [
        (0.42, (0.220, 0.230, 0.180, 1.0)),  # warm earth haze just below horizon
        (0.50, (0.850, 0.820, 0.720, 1.0)),  # cream-white horizon glow
        (0.55, (0.780, 0.840, 0.900, 1.0)),  # warm pale azure just above horizon
        (0.70, (0.520, 0.700, 0.880, 1.0)),  # mid-sky pale azure
        (0.88, (0.380, 0.620, 0.880, 1.0)),  # high-sky cyan-blue
        (1.00, (0.300, 0.560, 0.860, 1.0)),  # zenith cyan
    ]
    for pos, color in new_stops:
        el = cr.elements.new(pos)
        el.color = color

    # Map Z from [-1, 1] (sphere coords) to [0, 1] for the ColorRamp.
    add_node = nt.nodes.new("ShaderNodeMath")
    add_node.location = (-900, 100)
    add_node.operation = "ADD"
    add_node.inputs[1].default_value = 1.0
    nt.links.new(sep_xyz.outputs["Z"], add_node.inputs[0])

    mul_node = nt.nodes.new("ShaderNodeMath")
    mul_node.location = (-800, 100)
    mul_node.operation = "MULTIPLY"
    mul_node.inputs[1].default_value = 0.5
    nt.links.new(add_node.outputs[0], mul_node.inputs[0])
    nt.links.new(mul_node.outputs[0], color_ramp.inputs["Fac"])

    # Mountain horizon band — lush green Drakensberg silhouette.
    mountain_noise = nt.nodes.new("ShaderNodeTexNoise")
    mountain_noise.location = (-1100, -700)
    mountain_noise.inputs["Scale"].default_value = 4.0
    mountain_noise.inputs["Detail"].default_value = 6.0
    mountain_noise.inputs["Roughness"].default_value = 0.65
    if "Distortion" in mountain_noise.inputs:
        mountain_noise.inputs["Distortion"].default_value = 1.5
    nt.links.new(tex_coord.outputs["Generated"], mountain_noise.inputs["Vector"])

    noise_centre = nt.nodes.new("ShaderNodeMath")
    noise_centre.location = (-880, -700)
    noise_centre.operation = "SUBTRACT"
    noise_centre.inputs[1].default_value = 0.5
    nt.links.new(mountain_noise.outputs["Fac"], noise_centre.inputs[0])

    noise_amp = nt.nodes.new("ShaderNodeMath")
    noise_amp.location = (-700, -700)
    noise_amp.operation = "MULTIPLY"
    noise_amp.inputs[1].default_value = 0.12
    nt.links.new(noise_centre.outputs[0], noise_amp.inputs[0])

    # Bias ridge so its mean sits slightly above the panoramic equator —
    # mountains stand against the bright horizon haze.
    ridge_height = nt.nodes.new("ShaderNodeMath")
    ridge_height.location = (-520, -700)
    ridge_height.operation = "ADD"
    ridge_height.inputs[1].default_value = 0.030
    nt.links.new(noise_amp.outputs[0], ridge_height.inputs[0])

    elev_diff = nt.nodes.new("ShaderNodeMath")
    elev_diff.location = (-340, -700)
    elev_diff.operation = "SUBTRACT"
    nt.links.new(sep_xyz.outputs["Z"], elev_diff.inputs[0])
    nt.links.new(ridge_height.outputs[0], elev_diff.inputs[1])

    mountain_mask = nt.nodes.new("ShaderNodeMapRange")
    mountain_mask.location = (-160, -700)
    mountain_mask.inputs["From Min"].default_value = -0.010
    mountain_mask.inputs["From Max"].default_value = 0.010
    mountain_mask.inputs["To Min"].default_value = 1.0
    mountain_mask.inputs["To Max"].default_value = 0.0
    mountain_mask.clamp = True
    nt.links.new(elev_diff.outputs[0], mountain_mask.inputs["Value"])

    # Mountain colour — deep forest green (Drakensberg lush ridge).
    mountain_mix = nt.nodes.new("ShaderNodeMixRGB")
    mountain_mix.location = (100, -200)
    mountain_mix.blend_type = "MIX"
    mountain_mix.inputs["Color2"].default_value = (0.080, 0.180, 0.090, 1.0)
    nt.links.new(color_ramp.outputs["Color"], mountain_mix.inputs["Color1"])
    nt.links.new(mountain_mask.outputs["Result"], mountain_mix.inputs["Fac"])

    # Subtle low-frequency hue jitter on the mountains so adjacent ridges
    # don't read as a single flat colour — second noise modulates green.
    ridge_hue_noise = nt.nodes.new("ShaderNodeTexNoise")
    ridge_hue_noise.location = (-1100, -1100)
    ridge_hue_noise.inputs["Scale"].default_value = 8.0
    ridge_hue_noise.inputs["Detail"].default_value = 2.0
    ridge_hue_noise.inputs["Roughness"].default_value = 0.5
    nt.links.new(tex_coord.outputs["Generated"], ridge_hue_noise.inputs["Vector"])

    ridge_tint = nt.nodes.new("ShaderNodeMixRGB")
    ridge_tint.location = (-100, -1000)
    ridge_tint.blend_type = "MIX"
    # Slightly cooler / paler far-ridge tint to evoke atmospheric haze.
    ridge_tint.inputs["Color1"].default_value = (0.080, 0.180, 0.090, 1.0)
    ridge_tint.inputs["Color2"].default_value = (0.140, 0.220, 0.150, 1.0)
    nt.links.new(ridge_hue_noise.outputs["Fac"], ridge_tint.inputs["Fac"])

    # Re-apply the mountain mix using the modulated tint as Color2.
    mountain_tint_mix = nt.nodes.new("ShaderNodeMixRGB")
    mountain_tint_mix.location = (250, -300)
    mountain_tint_mix.blend_type = "MIX"
    nt.links.new(mountain_mix.outputs["Color"], mountain_tint_mix.inputs["Color1"])
    nt.links.new(ridge_tint.outputs["Color"], mountain_tint_mix.inputs["Color2"])
    # Mask: same mountain_mask × 0.6 so the tint only applies where mountains exist.
    tint_gate = nt.nodes.new("ShaderNodeMath")
    tint_gate.location = (50, -500)
    tint_gate.operation = "MULTIPLY"
    tint_gate.inputs[1].default_value = 0.6
    nt.links.new(mountain_mask.outputs["Result"], tint_gate.inputs[0])
    nt.links.new(tint_gate.outputs[0], mountain_tint_mix.inputs["Fac"])

    # Output background — pure gradient + mountains, no stars in daylight.
    bg = nt.nodes.new("ShaderNodeBackground")
    bg.location = (550, 0)
    # Strength bumped a bit so the daylight reads punchy through the windows.
    bg.inputs["Strength"].default_value = 1.4
    nt.links.new(mountain_tint_mix.outputs["Color"], bg.inputs["Color"])

    out = nt.nodes.new("ShaderNodeOutputWorld")
    out.location = (800, 0)
    nt.links.new(bg.outputs["Background"], out.inputs["Surface"])


def _setup_camera_and_render() -> None:
    bpy.context.scene.render.engine = "CYCLES"
    bpy.context.scene.cycles.samples = SAMPLES
    bpy.context.scene.cycles.use_denoising = True

    cam_data = bpy.data.cameras.new("Pano")
    cam_data.type = "PANO"
    cam_data.panorama_type = "EQUIRECTANGULAR"
    cam = bpy.data.objects.new("Pano", cam_data)
    bpy.context.scene.collection.objects.link(cam)
    cam.location = (0, 0, 0)
    cam.rotation_euler = (math.radians(90), 0, 0)
    bpy.context.scene.camera = cam

    bpy.context.scene.render.resolution_x = RESOLUTION_X
    bpy.context.scene.render.resolution_y = RESOLUTION_Y
    bpy.context.scene.render.resolution_percentage = 100
    bpy.context.scene.render.image_settings.file_format = "HDR"
    bpy.context.scene.render.image_settings.color_mode = "RGB"
    bpy.context.scene.render.filepath = str(OUTPUT_HDR)


def main() -> None:
    _reset_scene()
    _build_world_shader()
    _setup_camera_and_render()
    OUTPUT_HDR.parent.mkdir(parents=True, exist_ok=True)
    bpy.ops.render.render(write_still=True)
    print(f"  baked → {OUTPUT_HDR.relative_to(_REPO_ROOT)} ({OUTPUT_HDR.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
